# this is the playbook PB for this command
# ansible -b -m file -a "dest=/home/ansible/hello state=touch" localhost  ##  file module create hello on localhost
# no run
# ansible-playbook   yadayada.yaml -vv  << for verbose
- name: copy module ex
  hosts:  sys1
  tasks:
  - copy:
     dest: /home/ansible/hello
     content: "bunnies of the world unite"
  - command: date   #so see output   add -v   or -vvv   to make clearer
