---
- name: Install and start bind9
  hosts: sys1
  become: yes
  tasks:
    - name: Ensure bind9 is installed
      ansible.builtin.package:
        name: bind
        state: present

    - name: Ensure bind9 is running
      ansible.builtin.service:
        name: rpcbind
        state: started
        enabled: yes
