
- name: install bind9
  hosts: sys1
  tags: bind         ##   so if you add --tags bind   to the PB run  , it only runs   THIS name
  diff: true         ##   so runs diff even if not on set cmd line PB  command  , you can have diff on task also! 
  check_mode: true   ##  so doesn't run , just check to see  what would change/etc
  become: true       ##  become root , either this way or --become on PB command line
  tasks:
  - ansible.builtin.apt:
      update_cache: true  ##   aptget update  run  before bind install
      name: bind9, nginx
      tags: bind   ##  

