
- name: install bind9
  hosts: all     ##  so run against all but only run task if the criteria matches
  tags: bind        
  diff: true        
  become: true       ##  become root , either this way or --become on PB command line
  tasks: 
  - name: dump facts  ## so  get some info in client first!
    ansible.builtin.debug:   ## like ansible -m setup .. extacts info
      ##  like  ansible -m setup sys1 -a "filter=ansible_distribution"
      var: ansible_distributon  #   returns this > for example"ansible_distribution": "Ubuntu",
 # - name: Only run if OS is Ubuntu
 #   when: ansible_distributon  == "Ubuntu"
 #   ansible.builtin.apt:
 #     update_cache: true 
  #    pkg: 
   #   - "bind9"
   #   - "nginx"
   
      
