---
##test
- name: copy module ex
  hosts:  sys1
  tags: taggy    # if this tag is listed   ansible-playbook files.yaml --tags  taggy
  become: true
  tasks:
  - file: 
     dest: /home/ansible
     state: directory
  - copy:
     dest: /home/ansible/hello
     content: "bunnies of the world unite"
     owner: ansible
     group: ansible
     mode: '1777'
  - command: date
