---
##test
- name: copy module ex
  hosts:  sys1
  tags: taggy    # if this tag is listed   ansible-playbook files.yaml --tags  taggy
  tasks:
  - copy:
     dest: /home/ansible/hello
     content: "bunnies of the world unite"
  - command: date
