---
##test
- name: copy module ex
  hosts:  sys1
  tags: taggy    # if this tag is listed   ansible-playbook files.yaml --tags  taggy
  become: true
  tasks:
  - file: 
     dest: /home/ansible
     state: directory
     owner: ansible
     group: ansible
     mode: '0777'
  - copy:
     dest: /home/ansible/hello
     content: "bunnies of the world unite"
     owner: ansible
     group: ansible
     mode: '0777'
  - command: date
  - name: Ensure group "somegroup" exists
    ansible.builtin.group:
      name: ansible
      state: present