---
##  gather facts
- name: get all your fact straight
  hosts:  sys1
  gather_facts: false  ##    returns everything
  tasks: 
    - ansible.builtin.debug:
       var: ansible_facts  ##    returns everything


- name: get some of your fact straight
  hosts:  sys1
  gather_subset: 
       - processor  ##    returns everything
  tasks: 
    - ansible.builtin.debug:
       var: ansible_facts  ##    returns everything
    