---
##  gather facts
- name: get all your fact straight
  hosts:  sys1
  gather_facts: false  ##    returns everything
  tasks: 
    - ansible.builtin.debug:
       var: ansible_facts  ##    returns everything


- name: get some of your fact straight
  hosts:  sys1
  gather_subset:  # https://oneuptime.com/blog/post/2026-02-21-how-to-use-ansible-gather-subset-for-selective-fact-gathering/view#subset-reference
      - '!min'
      - distribution_version
  tasks: 
    #- name: show system #node-requirement-summary
      - ansible.builtin.debug:
          var: ansible_facts
