
- name: Build website Centos and Ubuntu
  hosts: all       ##   so if you add --tags bind   to the PB run  , it only runs   THIS name
  diff: true         ##   so runs diff even if not on set cmd line PB  command  , you can have diff on task also! 
  become: true       ##  become root , either this way or --become on PB command line
  tasks:
  - name: dump facts # so  get some info in client first!
    ansible.builtin.debug:
        var: ansible_distribution #   returns this > for example"ansible_distribution": "Ubuntu",
  - name: Only run if OS is Ubuntu
    when: ansible_distribution  == "Ubuntu"
    apt:
      update_cache: true  ##   aptget update  run  before bind install , equivalent to  "apt update"
      pkg:    # <<<  pkg or name
        - "nginx"
  - name: Only run if OS is Centos
    when: ansible_distribution  == "Centos"
    yum:
      pkg:  
        - "nginx"
  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: started
      name: nginx
