# Your user ( ansible) needs passwordless access with root auth  ie sudo NOPASSWD:ALL
#  install python , pip and ansible
#  update /etc/environment   to add allowable path to ansible cmd FROM  SOURCE  .. so NOT needed on client , but
# requirements
# https://docs.ansible.com/projects/ansible/latest/installation_guide/intro_installation.html#node-requirement-summary
/etc/sudo python --version
[[ -e `grep Red /etc/redhat-release` ]] && sudo yum install pip -y || sudo apt install pip -y
sudo python3 -m pip install --user ansible ## -m  runs pip as a module incase you have multiple versions

# echo "PATH=\"$PATH:/home/ansible/.local/bin\"">> /etc/environment   #  or whatever the path says
# echo "export EDITOR=vi">> /etc/environment   #  or whatever the path says
# pip3 list --user   # expect ansible
# git clone https://github.com/davehartx/ansible-DNS.git
# git config --global user.name "davehartx" 
# git config --global user.email "Dave_hartx@hotmail.com"
# git pull https://github.com/davehartx/ansible-DNS.git   ##    to get latest
#  TAB completions
# ansible -m pip -a "name=argcomplete" localhost  ##  if it doesn't work pip install argcomplete
# then >>  activate-global-python-argcomplete --user
##    CLEAN OUT SSH
# echo > .ssh/known_hosts


- hosts: workstation
  become: yes
  vars:
     target_package: httpd
     target_state: latest 
  tasks:
  - name: install httpd
    yum:
      name: "{{target_package}}"
      state: "{{target_state}}"
  - name: start httpd
    service:
      name: httpd
      enabled: yes
      state: started
